version: "3.9"
services:
  backend1:
    build:
      context: ./backend1

    #ports:
    #  - "5000:5000"
    expose:
      - "5000"

    networks:
      public_net:
        ipv4_address: ${backend_1_IP}

  backend2:
    build:
      context: ./backend2

    #ports:
    #  - "5000:5000"
    expose:
      - "5000"

    networks:
      public_net:
        ipv4_address: ${backend_2_IP}

  haproxy:
          build: ./haproxy
          volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - ./haproxy/blacklist_agent.lst:/usr/local/etc/haproxy/blacklist_agent.lst:ro
            - ./haproxy/whitelist_agent.lst:/usr/local/etc/haproxy/whitelist_agent.lst:ro

          ports:
              - 9090:80 #bind 80 on container to 9090 on host

          networks:
              public_net:
                  ipv4_address: ${HA_PROXY_IP}  

          environment:
              - backend_1_IP=${backend_1_IP}
              - backend_2_IP=${backend_2_IP}
              - backend_EXPOSED_PORT=${backend_EXPOSED_PORT} #exposed port is 5000, internal flask port.

          depends_on:
            - backend1
            - backend2
  
  prometheus:
      image: prom/prometheus:v2.1.0
      container_name: prometheus
      volumes:
        - ./prometheus/:/etc/prometheus/
        #- prometheus/:/prometheus/
      ports:
        - 9000:9000

      depends_on:
        - backend1
        - backend2
        - haproxy

      networks:
          public_net:
              ipv4_address: ${PROMETHEUS}
        
      command: 
        - '--web.listen-address=:9000'
        - '--config.file=/etc/prometheus/prometheus.yml'


networks:
    public_net:
        driver: bridge
        
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}